# Generated by Django 3.0.5 on 2020-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoriais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='opiniao',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Regular', 'Regular'), ('Ruim', 'Ruim')], default='Bom', max_length=7),
        ),
    ]
